import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { registerDiceTool } from "./tools/dice";
import { registerDBTools } from "./tools/db";
import { registerWorldGenTool } from "./tools/world-gen";
import { registerSkillCheckTool } from "./tools/skill-check";
import { registerCombatTool } from "./tools/combat";
import { registerLootTool } from "./tools/loot";
import { registerConsumeTool } from "./tools/consume";
import { registerCraftTool } from "./tools/craft";
import { registerTradeTool } from "./tools/trade";
import { registerStatusRuntimeTools } from "./tools/status-runtime";
import { registerLevelUpTool } from "./tools/level-up";
import { registerLegendaryGenTool } from "./tools/legendary-gen";
import { registerWeaponGenTool } from "./tools/weapon-gen";
import { registerArmorGenTool } from "./tools/armor-gen";
import { registerAccessoryGenTool } from "./tools/accessory-gen";
import { registerEquipTools } from "./tools/equip";
import { registerEventLogTools } from "./tools/event-log";
import { registerExplorationTools } from "./tools/exploration";
import { registerGMGuideTool } from "./tools/gm-guide";
import { registerEncounterTool } from "./tools/encounter";
import { registerTraderTool } from "./tools/trader";
import { registerLootGenTool } from "./tools/loot-gen";
import { registerTakeLootTool } from "./tools/take-loot";
import { registerTimeTools } from "./tools/time";
import { registerQuestTools } from "./tools/quest";
import { registerToolHelpTool } from "./tools/tool-help";

export default function (pi: ExtensionAPI) {
  registerDiceTool(pi);
  registerDBTools(pi);
  registerWorldGenTool(pi);
  registerSkillCheckTool(pi);
  registerCombatTool(pi);
  registerLootTool(pi);
  registerConsumeTool(pi);
  registerCraftTool(pi);
  registerTradeTool(pi);
  registerStatusRuntimeTools(pi);
  registerLevelUpTool(pi);
  registerLegendaryGenTool(pi);
  registerWeaponGenTool(pi);
  registerArmorGenTool(pi);
  registerAccessoryGenTool(pi);
  registerEquipTools(pi);
  registerEventLogTools(pi);
  registerExplorationTools(pi);
  registerGMGuideTool(pi);
  registerEncounterTool(pi);
  registerTraderTool(pi);
  registerLootGenTool(pi);
  registerTakeLootTool(pi);
  registerTimeTools(pi);
  registerQuestTools(pi);
  registerToolHelpTool(pi);

  pi.on("session_start", async (_event, ctx) => {
    ctx.ui.notify("⚙️ Chronika Engine loaded", "info");
  });
}
