// 初始怪物 — 废土风格
export const SEED_MONSTERS = [
  // ═══════════════════════ Tier 1 — 初期 (15种) ═══════════════════════
  { name: "辐射蟑螂", category: "beast", hp: 8, damage_min: 1, damage_max: 3, accuracy: 0.5, evasion: 0.4, armor: 1, tier: 1, xp_reward: 4,
    strength: 2, agility: 6, endurance: 3, perception: 3, intelligence: 1, willpower: 2 },
  { name: "变异鼠", category: "beast", hp: 12, damage_min: 2, damage_max: 4, accuracy: 0.6, evasion: 0.35, armor: 0, tier: 1, xp_reward: 6,
    strength: 3, agility: 5, endurance: 3, perception: 4, intelligence: 1, willpower: 1 },
  { name: "废土野狗", category: "beast", hp: 16, damage_min: 3, damage_max: 6, accuracy: 0.65, evasion: 0.3, armor: 1, tier: 1, xp_reward: 10,
    strength: 3, agility: 5, endurance: 3, perception: 3, intelligence: 1, willpower: 1 },
  { name: "浮肿蝇", category: "beast", hp: 7, damage_min: 2, damage_max: 5, accuracy: 0.5, evasion: 0.45, armor: 0, tier: 1, xp_reward: 5,
    strength: 2, agility: 5, endurance: 2, perception: 5, intelligence: 1, willpower: 2 },
  { name: "掠夺者喽啰", category: "humanoid", hp: 20, damage_min: 3, damage_max: 7, accuracy: 0.55, evasion: 0.25, armor: 2, tier: 1, xp_reward: 14,
    strength: 5, agility: 3, endurance: 3, perception: 3, intelligence: 2, willpower: 1 },
  { name: "辐射乌鸦", category: "beast", hp: 6, damage_min: 1, damage_max: 4, accuracy: 0.6, evasion: 0.5, armor: 0, tier: 1, xp_reward: 4,
    strength: 1, agility: 5, endurance: 2, perception: 5, intelligence: 1, willpower: 2 },
  { name: "荒地耗子", category: "beast", hp: 10, damage_min: 2, damage_max: 4, accuracy: 0.55, evasion: 0.3, armor: 0, tier: 1, xp_reward: 5,
    strength: 3, agility: 4, endurance: 3, perception: 4, intelligence: 1, willpower: 2 },
  { name: "毒蜂", category: "beast", hp: 6, damage_min: 1, damage_max: 6, accuracy: 0.5, evasion: 0.5, armor: 0, tier: 1, xp_reward: 6,
    strength: 1, agility: 5, endurance: 1, perception: 6, intelligence: 1, willpower: 2 },
  { name: "辐射蛞蝓", category: "beast", hp: 20, damage_min: 1, damage_max: 3, accuracy: 0.4, evasion: 0.05, armor: 3, tier: 1, xp_reward: 6,
    strength: 4, agility: 1, endurance: 5, perception: 2, intelligence: 1, willpower: 3 },
  { name: "废土猫", category: "beast", hp: 8, damage_min: 1, damage_max: 3, accuracy: 0.65, evasion: 0.5, armor: 0, tier: 1, xp_reward: 4,
    strength: 2, agility: 5, endurance: 2, perception: 5, intelligence: 1, willpower: 2 },
  { name: "变异蝌蚪", category: "beast", hp: 5, damage_min: 1, damage_max: 2, accuracy: 0.4, evasion: 0.3, armor: 0, tier: 1, xp_reward: 3,
    strength: 1, agility: 3, endurance: 2, perception: 3, intelligence: 1, willpower: 2 },
  { name: "辐射蚱蜢", category: "beast", hp: 7, damage_min: 1, damage_max: 4, accuracy: 0.5, evasion: 0.55, armor: 0, tier: 1, xp_reward: 5,
    strength: 2, agility: 6, endurance: 2, perception: 4, intelligence: 1, willpower: 2 },
  { name: "废土蜥蜴", category: "beast", hp: 10, damage_min: 2, damage_max: 5, accuracy: 0.6, evasion: 0.4, armor: 1, tier: 1, xp_reward: 6,
    strength: 3, agility: 4, endurance: 3, perception: 4, intelligence: 1, willpower: 2 },
  { name: "霉菌怪", category: "mutant", hp: 16, damage_min: 2, damage_max: 5, accuracy: 0.45, evasion: 0.1, armor: 1, tier: 1, xp_reward: 8,
    strength: 3, agility: 1, endurance: 4, perception: 2, intelligence: 1, willpower: 3 },
  { name: "掠夺者新兵", category: "humanoid", hp: 18, damage_min: 3, damage_max: 7, accuracy: 0.5, evasion: 0.2, armor: 1, tier: 1, xp_reward: 12,
    strength: 5, agility: 3, endurance: 4, perception: 2, intelligence: 1, willpower: 2 },

  // ═══════════════════════ Tier 2 — 中等 (15种) ═══════════════════════
  { name: "狂尸鬼", category: "mutant", hp: 28, damage_min: 4, damage_max: 10, accuracy: 0.55, evasion: 0.15, armor: 1, tier: 2, xp_reward: 20,
    strength: 7, agility: 3, endurance: 7, perception: 2, intelligence: 1, willpower: 5 },
  { name: "辐射蝎", category: "mutant", hp: 34, damage_min: 5, damage_max: 12, accuracy: 0.6, evasion: 0.25, armor: 6, tier: 2, xp_reward: 28,
    strength: 8, agility: 6, endurance: 7, perception: 5, intelligence: 1, willpower: 4 },
  { name: "鼹鼠", category: "beast", hp: 22, damage_min: 4, damage_max: 8, accuracy: 0.6, evasion: 0.3, armor: 2, tier: 2, xp_reward: 18,
    strength: 6, agility: 6, endurance: 5, perception: 7, intelligence: 2, willpower: 3 },
  { name: "掠夺者刀刃", category: "humanoid", hp: 28, damage_min: 5, damage_max: 11, accuracy: 0.6, evasion: 0.3, armor: 3, tier: 2, xp_reward: 22,
    strength: 8, agility: 7, endurance: 5, perception: 5, intelligence: 4, willpower: 5 },
  { name: "泥沼蟹", category: "beast", hp: 36, damage_min: 5, damage_max: 12, accuracy: 0.55, evasion: 0.15, armor: 8, tier: 2, xp_reward: 26,
    strength: 9, agility: 3, endurance: 9, perception: 4, intelligence: 2, willpower: 5 },
  { name: "废土商人护卫", category: "humanoid", hp: 26, damage_min: 4, damage_max: 10, accuracy: 0.6, evasion: 0.3, armor: 4, tier: 2, xp_reward: 22,
    strength: 7, agility: 5, endurance: 6, perception: 6, intelligence: 5, willpower: 5 },
  { name: "辐射水蛭", category: "beast", hp: 18, damage_min: 3, damage_max: 8, accuracy: 0.55, evasion: 0.2, armor: 0, tier: 2, xp_reward: 16,
    strength: 4, agility: 5, endurance: 4, perception: 4, intelligence: 1, willpower: 4 },
  { name: "变种豪猪", category: "beast", hp: 28, damage_min: 5, damage_max: 13, accuracy: 0.55, evasion: 0.2, armor: 4, tier: 2, xp_reward: 24,
    strength: 8, agility: 4, endurance: 7, perception: 5, intelligence: 2, willpower: 4 },
  { name: "掠夺者投火者", category: "humanoid", hp: 24, damage_min: 5, damage_max: 14, accuracy: 0.5, evasion: 0.25, armor: 2, tier: 2, xp_reward: 24,
    strength: 6, agility: 6, endurance: 4, perception: 6, intelligence: 4, willpower: 4 },
  { name: "辐射鸵鸟", category: "beast", hp: 30, damage_min: 5, damage_max: 11, accuracy: 0.6, evasion: 0.35, armor: 1, tier: 2, xp_reward: 22,
    strength: 8, agility: 7, endurance: 6, perception: 7, intelligence: 2, willpower: 4 },
  { name: "变异蜘蛛", category: "beast", hp: 24, damage_min: 4, damage_max: 10, accuracy: 0.6, evasion: 0.35, armor: 2, tier: 2, xp_reward: 20,
    strength: 6, agility: 8, endurance: 4, perception: 7, intelligence: 2, willpower: 3 },
  { name: "狂尸鬼暴徒", category: "mutant", hp: 36, damage_min: 6, damage_max: 14, accuracy: 0.55, evasion: 0.12, armor: 2, tier: 2, xp_reward: 26,
    strength: 9, agility: 3, endurance: 9, perception: 2, intelligence: 1, willpower: 6 },
  { name: "辐射鹰", category: "beast", hp: 18, damage_min: 4, damage_max: 10, accuracy: 0.7, evasion: 0.4, armor: 0, tier: 2, xp_reward: 20,
    strength: 5, agility: 10, endurance: 4, perception: 10, intelligence: 2, willpower: 3 },
  { name: "荒地响尾蛇", category: "beast", hp: 20, damage_min: 4, damage_max: 12, accuracy: 0.65, evasion: 0.35, armor: 1, tier: 2, xp_reward: 20,
    strength: 5, agility: 8, endurance: 4, perception: 7, intelligence: 1, willpower: 3 },
  { name: "掠夺者陷阱师", category: "humanoid", hp: 22, damage_min: 4, damage_max: 10, accuracy: 0.55, evasion: 0.3, armor: 2, tier: 2, xp_reward: 22,
    strength: 6, agility: 5, endurance: 5, perception: 8, intelligence: 5, willpower: 5 },

  // ═══════════════════════ Tier 3 — 危险 (15种) ═══════════════════════
  { name: "发光者", category: "mutant", hp: 42, damage_min: 6, damage_max: 15, accuracy: 0.6, evasion: 0.15, armor: 3, tier: 3, xp_reward: 38,
    strength: 9, agility: 3, endurance: 10, perception: 4, intelligence: 2, willpower: 7 },
  { name: "超级变种人", category: "humanoid", hp: 55, damage_min: 10, damage_max: 22, accuracy: 0.6, evasion: 0.2, armor: 6, tier: 3, xp_reward: 50,
    strength: 14, agility: 4, endurance: 12, perception: 5, intelligence: 3, willpower: 7 },
  { name: "妖怪", category: "beast", hp: 50, damage_min: 9, damage_max: 20, accuracy: 0.65, evasion: 0.2, armor: 5, tier: 3, xp_reward: 46,
    strength: 13, agility: 5, endurance: 11, perception: 6, intelligence: 2, willpower: 6 },
  { name: "夜枭", category: "beast", hp: 32, damage_min: 7, damage_max: 16, accuracy: 0.75, evasion: 0.4, armor: 2, tier: 3, xp_reward: 40,
    strength: 8, agility: 11, endurance: 5, perception: 9, intelligence: 3, willpower: 5 },
  { name: "掠夺者重装兵", category: "humanoid", hp: 48, damage_min: 8, damage_max: 18, accuracy: 0.6, evasion: 0.2, armor: 8, tier: 3, xp_reward: 42,
    strength: 11, agility: 4, endurance: 10, perception: 6, intelligence: 5, willpower: 6 },
  { name: "变种人追踪者", category: "humanoid", hp: 45, damage_min: 8, damage_max: 18, accuracy: 0.65, evasion: 0.3, armor: 5, tier: 3, xp_reward: 44,
    strength: 11, agility: 8, endurance: 8, perception: 8, intelligence: 4, willpower: 6 },
  { name: "辐射象", category: "beast", hp: 65, damage_min: 10, damage_max: 22, accuracy: 0.55, evasion: 0.1, armor: 8, tier: 3, xp_reward: 52,
    strength: 15, agility: 2, endurance: 14, perception: 4, intelligence: 2, willpower: 7 },
  { name: "掠夺者狙击手", category: "humanoid", hp: 35, damage_min: 8, damage_max: 20, accuracy: 0.8, evasion: 0.25, armor: 3, tier: 3, xp_reward: 45,
    strength: 7, agility: 9, endurance: 5, perception: 10, intelligence: 5, willpower: 5 },
  { name: "狂尸鬼集群", category: "mutant", hp: 55, damage_min: 7, damage_max: 16, accuracy: 0.5, evasion: 0.1, armor: 1, tier: 3, xp_reward: 44,
    strength: 10, agility: 4, endurance: 11, perception: 3, intelligence: 1, willpower: 7 },
  { name: "变异犀牛", category: "beast", hp: 60, damage_min: 10, damage_max: 24, accuracy: 0.55, evasion: 0.1, armor: 10, tier: 3, xp_reward: 50,
    strength: 15, agility: 2, endurance: 13, perception: 4, intelligence: 2, willpower: 7 },
  { name: "螳螂", category: "beast", hp: 38, damage_min: 7, damage_max: 16, accuracy: 0.65, evasion: 0.35, armor: 3, tier: 3, xp_reward: 40,
    strength: 9, agility: 10, endurance: 5, perception: 7, intelligence: 2, willpower: 4 },
  { name: "辐射水牛", category: "beast", hp: 58, damage_min: 8, damage_max: 20, accuracy: 0.55, evasion: 0.15, armor: 7, tier: 3, xp_reward: 46,
    strength: 13, agility: 3, endurance: 12, perception: 5, intelligence: 2, willpower: 6 },
  { name: "掠夺者药剂师", category: "humanoid", hp: 34, damage_min: 6, damage_max: 16, accuracy: 0.6, evasion: 0.3, armor: 2, tier: 3, xp_reward: 40,
    strength: 7, agility: 7, endurance: 5, perception: 7, intelligence: 8, willpower: 5 },
  { name: "变种人重装兵", category: "humanoid", hp: 62, damage_min: 12, damage_max: 25, accuracy: 0.55, evasion: 0.15, armor: 10, tier: 3, xp_reward: 54,
    strength: 15, agility: 3, endurance: 13, perception: 5, intelligence: 3, willpower: 8 },
  { name: "荒地幽灵", category: "mutant", hp: 36, damage_min: 6, damage_max: 15, accuracy: 0.7, evasion: 0.45, armor: 1, tier: 3, xp_reward: 42,
    strength: 7, agility: 12, endurance: 4, perception: 10, intelligence: 3, willpower: 6 },

  // ═══════════════════════ Tier 4 — 精英 (15种) ═══════════════════════
  { name: "死亡爪", category: "mutant", hp: 75, damage_min: 15, damage_max: 32, accuracy: 0.8, evasion: 0.35, armor: 10, tier: 4, xp_reward: 85,
    strength: 18, agility: 10, endurance: 12, perception: 8, intelligence: 3, willpower: 8 },
  { name: "军械库机器人", category: "mechanical", hp: 60, damage_min: 10, damage_max: 24, accuracy: 0.85, evasion: 0.2, armor: 14, tier: 4, xp_reward: 72,
    strength: 14, agility: 4, endurance: 14, perception: 8, intelligence: 6, willpower: 10 },
  { name: "超级变种人军阀", category: "humanoid", hp: 72, damage_min: 12, damage_max: 28, accuracy: 0.65, evasion: 0.2, armor: 10, tier: 4, xp_reward: 68,
    strength: 16, agility: 5, endurance: 14, perception: 6, intelligence: 5, willpower: 8 },
  { name: "螳螂蝇", category: "beast", hp: 38, damage_min: 8, damage_max: 18, accuracy: 0.7, evasion: 0.45, armor: 1, tier: 4, xp_reward: 58,
    strength: 7, agility: 13, endurance: 4, perception: 10, intelligence: 2, willpower: 4 },
  { name: "死亡爪幼体", category: "mutant", hp: 50, damage_min: 10, damage_max: 22, accuracy: 0.75, evasion: 0.4, armor: 6, tier: 4, xp_reward: 65,
    strength: 13, agility: 12, endurance: 8, perception: 7, intelligence: 3, willpower: 6 },
  { name: "军械库MK2", category: "mechanical", hp: 75, damage_min: 12, damage_max: 28, accuracy: 0.8, evasion: 0.2, armor: 16, tier: 4, xp_reward: 80,
    strength: 16, agility: 5, endurance: 16, perception: 9, intelligence: 7, willpower: 12 },
  { name: "变种人巨人", category: "humanoid", hp: 85, damage_min: 14, damage_max: 30, accuracy: 0.55, evasion: 0.1, armor: 8, tier: 4, xp_reward: 72,
    strength: 17, agility: 2, endurance: 16, perception: 4, intelligence: 2, willpower: 8 },
  { name: "掠夺者将军", category: "humanoid", hp: 65, damage_min: 11, damage_max: 25, accuracy: 0.7, evasion: 0.3, armor: 10, tier: 4, xp_reward: 70,
    strength: 13, agility: 8, endurance: 10, perception: 8, intelligence: 7, willpower: 8 },
  { name: "辐射巨蟒", category: "beast", hp: 55, damage_min: 10, damage_max: 24, accuracy: 0.7, evasion: 0.3, armor: 4, tier: 4, xp_reward: 62,
    strength: 12, agility: 7, endurance: 9, perception: 6, intelligence: 2, willpower: 6 },
  { name: "电子脑人", category: "humanoid", hp: 50, damage_min: 8, damage_max: 22, accuracy: 0.75, evasion: 0.3, armor: 5, tier: 4, xp_reward: 66,
    strength: 8, agility: 8, endurance: 6, perception: 10, intelligence: 12, willpower: 7 },
  { name: "变异王蟹", category: "beast", hp: 70, damage_min: 10, damage_max: 24, accuracy: 0.55, evasion: 0.1, armor: 16, tier: 4, xp_reward: 68,
    strength: 14, agility: 2, endurance: 14, perception: 5, intelligence: 2, willpower: 6 },
  { name: "死亡爪母兽", category: "mutant", hp: 90, damage_min: 16, damage_max: 35, accuracy: 0.75, evasion: 0.3, armor: 12, tier: 4, xp_reward: 90,
    strength: 19, agility: 8, endurance: 14, perception: 8, intelligence: 3, willpower: 9 },
  { name: "军械库无人机群", category: "mechanical", hp: 40, damage_min: 8, damage_max: 20, accuracy: 0.8, evasion: 0.4, armor: 4, tier: 4, xp_reward: 64,
    strength: 6, agility: 14, endurance: 4, perception: 12, intelligence: 5, willpower: 8 },
  { name: "掠夺者技术狂", category: "humanoid", hp: 45, damage_min: 10, damage_max: 26, accuracy: 0.75, evasion: 0.25, armor: 6, tier: 4, xp_reward: 68,
    strength: 8, agility: 7, endurance: 5, perception: 9, intelligence: 10, willpower: 6 },
  { name: "辐射巨蛙", category: "beast", hp: 48, damage_min: 8, damage_max: 20, accuracy: 0.6, evasion: 0.3, armor: 3, tier: 4, xp_reward: 58,
    strength: 10, agility: 9, endurance: 7, perception: 7, intelligence: 2, willpower: 5 },

  // ═══════════════════════ Tier 5 — Boss (15种) ═══════════════════════
  { name: "阿尔法死亡爪", category: "mutant", hp: 110, damage_min: 20, damage_max: 45, accuracy: 0.85, evasion: 0.35, armor: 14, tier: 5, xp_reward: 140,
    strength: 20, agility: 12, endurance: 14, perception: 9, intelligence: 4, willpower: 10 },
  { name: "废土暴君", category: "humanoid", hp: 95, damage_min: 16, damage_max: 35, accuracy: 0.75, evasion: 0.35, armor: 16, tier: 5, xp_reward: 125,
    strength: 16, agility: 10, endurance: 12, perception: 9, intelligence: 8, willpower: 10 },
  { name: "战争机器", category: "mechanical", hp: 105, damage_min: 15, damage_max: 35, accuracy: 0.8, evasion: 0.15, armor: 20, tier: 5, xp_reward: 150,
    strength: 18, agility: 3, endurance: 18, perception: 10, intelligence: 6, willpower: 12 },
  { name: "死亡爪领主", category: "mutant", hp: 130, damage_min: 22, damage_max: 48, accuracy: 0.85, evasion: 0.3, armor: 16, tier: 5, xp_reward: 160,
    strength: 20, agility: 11, endurance: 15, perception: 9, intelligence: 4, willpower: 11 },
  { name: "天网核心", category: "mechanical", hp: 90, damage_min: 14, damage_max: 32, accuracy: 0.9, evasion: 0.25, armor: 18, tier: 5, xp_reward: 140,
    strength: 14, agility: 8, endurance: 12, perception: 14, intelligence: 12, willpower: 14 },
  { name: "变种人皇帝", category: "humanoid", hp: 120, damage_min: 18, damage_max: 40, accuracy: 0.7, evasion: 0.15, armor: 14, tier: 5, xp_reward: 145,
    strength: 20, agility: 4, endurance: 18, perception: 6, intelligence: 6, willpower: 10 },
  { name: "辐射巨兽", category: "mutant", hp: 150, damage_min: 18, damage_max: 42, accuracy: 0.6, evasion: 0.05, armor: 16, tier: 5, xp_reward: 155,
    strength: 20, agility: 1, endurance: 20, perception: 3, intelligence: 1, willpower: 9 },
  { name: "军械库泰坦", category: "mechanical", hp: 130, damage_min: 18, damage_max: 38, accuracy: 0.75, evasion: 0.1, armor: 22, tier: 5, xp_reward: 165,
    strength: 20, agility: 2, endurance: 20, perception: 8, intelligence: 6, willpower: 14 },
  { name: "掠夺者皇帝", category: "humanoid", hp: 100, damage_min: 16, damage_max: 36, accuracy: 0.8, evasion: 0.35, armor: 18, tier: 5, xp_reward: 130,
    strength: 17, agility: 12, endurance: 12, perception: 10, intelligence: 9, willpower: 11 },
  { name: "传说发光者", category: "mutant", hp: 85, damage_min: 12, damage_max: 28, accuracy: 0.65, evasion: 0.2, armor: 8, tier: 5, xp_reward: 120,
    strength: 12, agility: 5, endurance: 14, perception: 6, intelligence: 4, willpower: 14 },
  { name: "死亡爪女王", category: "mutant", hp: 160, damage_min: 24, damage_max: 50, accuracy: 0.85, evasion: 0.3, armor: 18, tier: 5, xp_reward: 180,
    strength: 20, agility: 10, endurance: 18, perception: 10, intelligence: 5, willpower: 12 },
  { name: "旧世界机器人", category: "mechanical", hp: 100, damage_min: 14, damage_max: 30, accuracy: 0.85, evasion: 0.2, armor: 20, tier: 5, xp_reward: 145,
    strength: 16, agility: 6, endurance: 16, perception: 12, intelligence: 8, willpower: 14 },
  { name: "辐射神灵", category: "mutant", hp: 140, damage_min: 20, damage_max: 45, accuracy: 0.8, evasion: 0.4, armor: 12, tier: 5, xp_reward: 170,
    strength: 18, agility: 14, endurance: 16, perception: 12, intelligence: 6, willpower: 16 },
  { name: "机械蝎王", category: "mechanical", hp: 95, damage_min: 14, damage_max: 32, accuracy: 0.75, evasion: 0.25, armor: 22, tier: 5, xp_reward: 148,
    strength: 16, agility: 6, endurance: 14, perception: 8, intelligence: 6, willpower: 12 },
  { name: "终极合成人", category: "humanoid", hp: 85, damage_min: 14, damage_max: 30, accuracy: 0.85, evasion: 0.4, armor: 12, tier: 5, xp_reward: 135,
    strength: 15, agility: 12, endurance: 10, perception: 12, intelligence: 14, willpower: 12 },
];

// 初始物品（消耗品 + 杂项）
export const SEED_ITEMS = [
  // 治疗类
  { name: "绷带", item_type: "consumable", rarity: "common", value: 8, weight: 0.1, effect_type: "heal", effect_value: 12, stackable: true, stack_max: 20 },
  { name: "治疗粉", item_type: "consumable", rarity: "common", value: 15, weight: 0.2, effect_type: "heal", effect_value: 20, stackable: true, stack_max: 15 },
  { name: "纯净水", item_type: "consumable", rarity: "common", value: 10, weight: 0.5, effect_type: "heal", effect_value: 10, stackable: true, stack_max: 10 },
  { name: "罐头", item_type: "consumable", rarity: "common", value: 12, weight: 0.4, effect_type: "heal", effect_value: 8, stackable: true, stack_max: 10 },
  { name: "止痛药", item_type: "consumable", rarity: "common", value: 10, weight: 0.1, effect_type: "heal", effect_value: 15, stackable: true, stack_max: 15 },
  { name: "消毒酒精", item_type: "consumable", rarity: "uncommon", value: 18, weight: 0.3, effect_type: "heal", effect_value: 18, stackable: true, stack_max: 10 },
  { name: "急救包", item_type: "consumable", rarity: "uncommon", value: 35, weight: 0.5, effect_type: "heal", effect_value: 35, stackable: false, stack_max: null },
  { name: "战斗兴奋剂", item_type: "consumable", rarity: "rare", value: 50, weight: 0.2, effect_type: "heal", effect_value: 45, stackable: true, stack_max: 5 },
  { name: "医疗箱", item_type: "consumable", rarity: "rare", value: 80, weight: 1.0, effect_type: "restore", effect_value: 0, stackable: false, stack_max: null },

  // 杂项
  { name: "瓶盖", item_type: "misc", rarity: "common", value: 1, weight: 0.01, effect_type: null, effect_value: null, stackable: true, stack_max: 999 },
  { name: "弹药", item_type: "misc", rarity: "common", value: 8, weight: 0.2, effect_type: null, effect_value: null, stackable: true, stack_max: 100 },
  { name: "能量电池", item_type: "misc", rarity: "uncommon", value: 25, weight: 0.5, effect_type: null, effect_value: null, stackable: true, stack_max: 20 },
  { name: "信号弹", item_type: "misc", rarity: "common", value: 15, weight: 0.3, effect_type: null, effect_value: null, stackable: true, stack_max: 10 },
];

// 初始状态效果
export const SEED_STATUS_EFFECTS = [
  { name: "流血", effect_type: "dot", target_attribute: "hp", magnitude: -3, duration: 3, description: "伤口不断失血，每回合损失 3 HP" },
  { name: "灼烧", effect_type: "dot", target_attribute: "hp", magnitude: -5, duration: 2, description: "火焰灼烧身体，每回合损失 5 HP" },
  { name: "中毒", effect_type: "dot", target_attribute: "hp", magnitude: -4, duration: 4, description: "毒素在血液中蔓延，每回合损失 4 HP" },
  { name: "辐射中毒", effect_type: "dot", target_attribute: "hp", magnitude: -6, duration: 3, description: "过量辐射侵蚀身体，每回合损失 6 HP" },
  { name: "愈合", effect_type: "hot", target_attribute: "hp", magnitude: 4, duration: 3, description: "伤口在药物作用下缓慢恢复，每回合回复 4 HP" },
  { name: "肾上腺素", effect_type: "buff", target_attribute: "strength", magnitude: 3, duration: 3, description: "战斗兴奋剂让你力量大增" },
  { name: "敏捷增强", effect_type: "buff", target_attribute: "agility", magnitude: 3, duration: 3, description: "身体变得轻盈灵活" },
  { name: "感知提升", effect_type: "buff", target_attribute: "perception", magnitude: 2, duration: 4, description: "感官变得异常敏锐" },
  { name: "力竭", effect_type: "debuff", target_attribute: "agility", magnitude: -2, duration: 3, description: "体力透支，动作变得迟缓" },
  { name: "恐惧", effect_type: "debuff", target_attribute: "willpower", magnitude: -3, duration: 2, description: "面对恐怖存在，意志崩溃" },
  { name: "麻痹", effect_type: "stun", target_attribute: "agility", magnitude: 0, duration: 1, description: "身体僵硬，无法行动" },
  { name: "致盲", effect_type: "debuff", target_attribute: "perception", magnitude: -4, duration: 2, description: "眼睛受伤，视野模糊" },
];

// 初始地点
export const SEED_LOCATIONS = [
  { name: "铁锈镇", region: "中心区域", description: "一座由废墟改建的小镇，四周用铁皮和木板围起了简陋的围墙。镇上有几家商铺、一间酒馆和零散的民居。这里是这片废土上少数还有秩序的地方。", danger_level: 1, has_shelter: true },
  { name: "废弃公路", region: "中心区域", description: "一条贯穿废土的旧公路，路面开裂，杂草丛生。两旁散落着生锈的汽车残骸和破碎的玻璃。偶尔能看到路标，但上面的字迹早已模糊不清。", danger_level: 2, has_shelter: false },
  { name: "东部废墟", region: "东部", description: "一座被炸毁的城市的残骸。高楼倒塌，街道被瓦砾堵塞。废墟中可能藏着有用的物资，但也可能有危险的东西在暗处窥视。", danger_level: 3, has_shelter: false },
  { name: "辐射洼地", region: "东部", description: "一片被辐射污染的洼地，空气中弥漫着淡绿色的雾气。地面龟裂，偶尔能看到发光的晶体。这里的生物都发生了可怕的变异。", danger_level: 4, has_shelter: false },
  { name: "旧水坝", region: "北部", description: "一座废弃的巨大水坝，混凝土结构历经数十年依然坚固。水坝内部黑暗潮湿，回响着滴水声。据说这里藏着旧世界的科技遗产。", danger_level: 3, has_shelter: false },
  { name: "南部集市", region: "南部", description: "一个由流浪商人自发形成的露天集市。帐篷和货摊杂乱地排列着，各种废土特产在此交易。这里没有法律，只有枪杆子说了算。", danger_level: 2, has_shelter: true },
  { name: "地下掩体", region: "北部", description: "一座旧世界的核辐射避难所，厚重的铁门半掩着。里面黑暗、寂静，空气沉闷。可能还有幸存者，也可能只剩下尸骸。", danger_level: 3, has_shelter: true },
  { name: "废弃工厂", region: "西部", description: "一座巨大的工业厂房，锈蚀的钢铁骨架在风中发出呻吟。机器早已停转，但仓库里或许还封存着有用的物资。", danger_level: 3, has_shelter: false },
  { name: "死亡爪峡谷", region: "东部", description: "一条蜿蜒的红色峡谷，两侧岩壁上布满了巨大的爪痕。这里是死亡爪的领地，空气中弥漫着血腥味。", danger_level: 5, has_shelter: false },
  { name: "避难所市集", region: "南部", description: "地下掩体入口处形成的小型聚居地，居民相对友好，有固定的交易场所和简单的医疗服务。", danger_level: 1, has_shelter: true },
  { name: "辐射湖", region: "西部", description: "一片因核污染而发出幽蓝光芒的湖泊，湖水含有剧毒。岸边寸草不生，但湖中似乎有某种生物在游动。", danger_level: 4, has_shelter: false },
  { name: "废铁城", region: "北部", description: "一座用废铁和汽车残骸搭建的堡垒城市，由一位自封的“废铁王”统治。城内有铁匠铺、武器店和竞技场。", danger_level: 3, has_shelter: true },
  { name: "寂静森林", region: "西部", description: "一片被辐射扭曲的森林，树木形态怪异，枝叶发出微弱的荧光。林间雾气弥漫，能见度极低。", danger_level: 3, has_shelter: false },
  { name: "军械库遗址", region: "北部", description: "一座旧世界军事基地的废墟，地下仓库可能还保存着武器和弹药。但基地的自动防御系统可能还在运行。", danger_level: 4, has_shelter: false },
  { name: "荒原车站", region: "中心区域", description: "一座废弃的火车站，铁轨锈蚀，月台裂缝中长出杂草。候车室里偶尔有流浪者过夜，墙上涂满了旧时代的涂鸦。", danger_level: 2, has_shelter: true },
];

// 地点连接
export const SEED_CONNECTIONS = [
  { from_location: "铁锈镇", to_location: "废弃公路", distance_km: 2, description: "一条从铁锈镇向东延伸的旧公路" },
  { from_location: "废弃公路", to_location: "东部废墟", distance_km: 3, description: "公路在废墟边缘终止" },
  { from_location: "东部废墟", to_location: "辐射洼地", distance_km: 5, description: "穿过废墟后方的污染区" },
  { from_location: "铁锈镇", to_location: "南部集市", distance_km: 4, description: "向南的土路，路面还算平整" },
  { from_location: "铁锈镇", to_location: "废弃工厂", distance_km: 6, description: "向西的旧铁路线" },
  { from_location: "废弃工厂", to_location: "辐射湖", distance_km: 3, description: "工厂后门的排污路" },
  { from_location: "铁锈镇", to_location: "旧水坝", distance_km: 8, description: "向北的旧公路，路况较差" },
  { from_location: "旧水坝", to_location: "地下掩体", distance_km: 2, description: "水坝后山的隐蔽小径" },
  { from_location: "旧水坝", to_location: "废铁城", distance_km: 5, description: "绕过山脚的泥土路" },
  { from_location: "东部废墟", to_location: "死亡爪峡谷", distance_km: 7, description: "穿过断裂的高速公路" },
  { from_location: "南部集市", to_location: "避难所市集", distance_km: 1, description: "集市北面的地下入口" },
  { from_location: "废弃公路", to_location: "荒原车站", distance_km: 2, description: "公路旁的一条岔路" },
  { from_location: "废弃工厂", to_location: "寂静森林", distance_km: 4, description: "工厂西面的林间小道" },
  { from_location: "军械库遗址", to_location: "废铁城", distance_km: 3, description: "军事基地通往废铁城的通道" },
  { from_location: "军械库遗址", to_location: "地下掩体", distance_km: 4, description: "山间小路连接两地" },
];
